<a href="https://colab.research.google.com/github/SAKETH-ui/24AG1A6697/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import numpy in python**

In [2]:
import numpy as np

import numpy creation

In [3]:
list=[2,3,4,5]
array1=np.array(list)
print(array1)

[2 3 4 5]


In [4]:
arrsy2=np.array([2,1,3,2,2])
print(arrsy2)

[2 1 3 2 2]


Creating a 2D array

In [5]:
array3=np.array([[1,3,2,4],[6,4,4,3]])
print(array3)

[[1 3 2 4]
 [6 4 4 3]]


Printing 3D array

In [9]:
array4=np.array([[[1,2,3,4],[3,4,57,6],[4,5,6,2]],[[234,4,3,2],[23,42,2,2],[3,2,35,7]]])
print(array4)
print(array4.ndim)
print(array.size)
print(array.itemsize)

[[[  1   2   3   4]
  [  3   4  57   6]
  [  4   5   6   2]]

 [[234   4   3   2]
  [ 23  42   2   2]
  [  3   2  35   7]]]
3
24
8


In [10]:
array5=np.array([1,3,32,4])
print(array5.dtype)
print(array5.size)

int64
4


check the datatype of given array

In [11]:
print(array5.ndim)

1


numpy shape attribute

In [13]:
array6=np.array([[1,3,325,2],[5,4,6,3]])
print(array6.shape)

(2, 4)


In [14]:
arr1=np.array([1,2,3,4])
arr2=np.array([[2,3,4,5],[4,5,6,7]])
print(arr1.data)
print(arr2.data)